using System;
using System.Collections.Generic;
using System.Windows.Forms;

namespace SysBot.Pokemon.WinForms;

public static class UILocalizer
{
    public static readonly Dictionary<string, Dictionary<string, string>> Translations = new()
    {
        ["en"] = new()
        {
            ["B_NavBots"] = "  Bots",
            ["B_NavHub"] = "  Settings",
            ["B_NavLogs"] = "  Logs",
            ["B_Credits"] = "  Credits",
            ["B_HideTray"] = "  Hide to Tray",
            ["B_Start"] = "Start All",
            ["B_Stop"] = "Stop All",
            ["B_Restart"] = "Restart All",
            ["B_Update"] = "Update",
            ["B_New"] = "Add",
            ["L_Language"] = "Language:",
            ["Tab_Bots"] = "Bots",
            ["Tab_Hub"] = "Settings",
            ["Tab_Logs"] = "Logs",
            ["Tab_Credits"] = "Credits",
            ["L_CreditsDevTitle"] = "Main Developer",
            ["L_CreditsContribTitle"] = "Project Contributors",
            ["L_CreditsSpecialTitle"] = "Special Thanks To",
            ["Idle"] = "Idle",
            ["FlexTrade"] = "Flex Trade",
            ["MultiTrade"] = "Multi Trade",
            ["LinkTrade"] = "Link Trade",
            ["SurpriseTrade"] = "Surprise Trade",
            ["Batch"] = "Batch",
            ["SeedCheck"] = "Seed Check",
            ["Clone"] = "Clone",
            ["Dump"] = "Dump",
            ["RaidBot"] = "Raid Bot",
            ["EncounterLine"] = "Encounter (Walk)",
            ["Reset"] = "Encounter (Reset)",
            ["DogBot"] = "Legend Bot",
            ["EggFetch"] = "Egg Fetch",
            ["FossilBot"] = "Fossil Bot",
            ["RemoteControl"] = "Remote Control",
            ["LGPE"] = "LGPE",
            ["SWSH"] = "SWSH",
            ["BDSP"] = "BDSP",
            ["LA"] = "LA",
            ["SV"] = "SV",
            ["PLZA"] = "PLZA",
            ["Dark Theme"] = "Dark Theme",
            ["Light Theme"] = "Light Theme",
            ["IP Address"] = "IP Address",
            ["Port"] = "Port",
            ["Protocol"] = "Protocol",
            ["Routine"] = "Routine",
            ["WiFi"] = "WiFi",
            ["USB"] = "USB",
            ["Status"] = "Status",
            ["Remove"] = "Remove",
            ["Resume"] = "Resume",
            ["RebootAndStop"] = "Reboot and Stop",
        },
        ["zh-Hans"] = new()
        {
            ["B_NavBots"] = "  机器人",
            ["B_NavHub"] = "  设置",
            ["B_NavLogs"] = "  日志",
            ["B_Credits"] = "  致谢",
            ["B_HideTray"] = "  隐藏到托盘",
            ["B_Start"] = "启动全部",
            ["B_Stop"] = "停止全部",
            ["B_Restart"] = "重启全部",
            ["B_Update"] = "更新",
            ["B_New"] = "添加",
            ["L_Language"] = "界面语言:",
            ["Tab_Bots"] = "机器人",
            ["Tab_Hub"] = "设置",
            ["Tab_Logs"] = "日志",
            ["Tab_Credits"] = "致谢",
            ["L_CreditsDevTitle"] = "主要开发人员",
            ["L_CreditsContribTitle"] = "项目贡献者",
            ["L_CreditsSpecialTitle"] = "特别鸣谢",
            ["Idle"] = "空闲",
            ["FlexTrade"] = "弹性交换",
            ["MultiTrade"] = "多重交换",
            ["LinkTrade"] = "连接交换",
            ["SurpriseTrade"] = "魔法交换",
            ["Batch"] = "批量交换",
            ["SeedCheck"] = "种子检查",
            ["Clone"] = "克隆",
            ["Dump"] = "转储",
            ["RaidBot"] = "团战机器人",
            ["EncounterLine"] = "遭遇战 (走路)",
            ["Reset"] = "遭遇战 (重置)",
            ["DogBot"] = "剑盾神兽",
            ["EggFetch"] = "蛋收集",
            ["FossilBot"] = "化石机器人",
            ["RemoteControl"] = "远程控制",
            ["LGPE"] = "皮伊",
            ["SWSH"] = "剑盾",
            ["BDSP"] = "珍钻",
            ["LA"] = "阿尔宙斯",
            ["SV"] = "朱紫",
            ["PLZA"] = "Z-A",
            ["Dark Theme"] = "深色主题",
            ["Light Theme"] = "浅色主题",
            ["IP Address"] = "IP地址",
            ["Port"] = "端口",
            ["Protocol"] = "协议",
            ["Routine"] = "例程",
            ["WiFi"] = "无线连接",
            ["USB"] = "串行连接",
            ["Status"] = "状态",
        },
        ["zh-Hant"] = new()
        {
            ["B_NavBots"] = "  機器人",
            ["B_NavHub"] = "  設定",
            ["B_NavLogs"] = "  日誌",
            ["B_Credits"] = "  鳴謝",
            ["B_HideTray"] = "  隱藏到系統匣",
            ["B_Start"] = "啟動全部",
            ["B_Stop"] = "停止全部",
            ["B_Restart"] = "重啟全部",
            ["B_Update"] = "更新",
            ["B_New"] = "新增",
            ["L_Language"] = "介面語言:",
            ["Tab_Bots"] = "機器人",
            ["Tab_Hub"] = "設定",
            ["Tab_Logs"] = "日誌",
            ["Tab_Credits"] = "鳴謝",
            ["L_CreditsDevTitle"] = "主要開發人員",
            ["L_CreditsContribTitle"] = "專案貢獻者",
            ["L_CreditsSpecialTitle"] = "特別鳴謝",
            ["Idle"] = "閒置",
            ["FlexTrade"] = "彈性交換",
            ["MultiTrade"] = "多重交換",
            ["LinkTrade"] = "連接交換",
            ["SurpriseTrade"] = "魔法交換",
            ["Batch"] = "批量交換",
            ["SeedCheck"] = "種子檢查",
            ["Clone"] = "克隆",
            ["Dump"] = "轉儲",
            ["RaidBot"] = "團戰機器人",
            ["EncounterLine"] = "遭遇戰 (走路)",
            ["Reset"] = "遭遇戰 (重置)",
            ["DogBot"] = "劍盾神獸",
            ["EggFetch"] = "蛋收集",
            ["FossilBot"] = "化石機器人",
            ["RemoteControl"] = "遠程控制",
            ["LGPE"] = "皮伊",
            ["SWSH"] = "劍盾",
            ["BDSP"] = "珍鑽",
            ["LA"] = "阿爾宙斯",
            ["SV"] = "朱紫",
            ["PLZA"] = "Z-A",
            ["Dark Theme"] = "深色主題",
            ["Light Theme"] = "淺色主題",
            ["IP Address"] = "IP位址",
            ["Port"] = "通訊埠",
            ["Protocol"] = "協定",
            ["Routine"] = "常式",
            ["WiFi"] = "無線連接",
            ["USB"] = "序列連接",
            ["Status"] = "狀態",
        },
        ["fr"] = new()
        {
            ["B_NavBots"] = "  Bots",
            ["B_NavHub"] = "  Paramètres",
            ["B_NavLogs"] = "  Journaux",
            ["B_Credits"] = "  Crédits",
            ["B_HideTray"] = "  Masquer",
            ["B_Start"] = "Démarrer tout",
            ["B_Stop"] = "Arrêter tout",
            ["B_Restart"] = "Redémarrer tout",
            ["B_Update"] = "Mise à jour",
            ["B_New"] = "Ajouter",
            ["L_Language"] = "Langue:",
            ["Tab_Bots"] = "Bots",
            ["Tab_Hub"] = "Paramètres",
            ["Tab_Logs"] = "Journaux",
            ["Tab_Credits"] = "Crédits",
            ["L_CreditsDevTitle"] = "Développeur Principal",
            ["L_CreditsContribTitle"] = "Contributeurs",
            ["L_CreditsSpecialTitle"] = "Remerciements",
            ["Idle"] = "Inactif",
            ["FlexTrade"] = "Échange Flex",
            ["MultiTrade"] = "Multi-échange",
            ["LinkTrade"] = "Échange Link",
            ["SurpriseTrade"] = "Échange Miracle",
            ["Batch"] = "Échange Lot",
            ["SeedCheck"] = "Vérif Graine",
            ["Clone"] = "Clonage",
            ["Dump"] = "Extraction",
            ["RaidBot"] = "Bot de Raid",
            ["EncounterLine"] = "Rencontre (Marche)",
            ["Reset"] = "Rencontre (Reset)",
            ["DogBot"] = "Bot Légendaires",
            ["EggFetch"] = "Collecte d'œufs",
            ["FossilBot"] = "Bot Fossile",
            ["RemoteControl"] = "Contrôle à distance",
            ["LGPE"] = "LGPE",
            ["SWSH"] = "EB",
            ["BDSP"] = "DEPS",
            ["LA"] = "LPA",
            ["SV"] = "EV",
            ["PLZA"] = "PLZA",
            ["Dark Theme"] = "Thème Sombre",
            ["Light Theme"] = "Thème Clair",
            ["IP Address"] = "Adresse IP",
            ["Port"] = "Port",
            ["Protocol"] = "Protocole",
            ["Routine"] = "Routine",
            ["WiFi"] = "WiFi",
            ["USB"] = "USB",
            ["Status"] = "Statut",
        },
        ["de"] = new()
        {
            ["B_NavBots"] = "  Bots",
            ["B_NavHub"] = "  Einstellungen",
            ["B_NavLogs"] = "  Logs",
            ["B_Credits"] = "  Credits",
            ["B_HideTray"] = "  Minimieren",
            ["B_Start"] = "Alle starten",
            ["B_Stop"] = "Alle stoppen",
            ["B_Restart"] = "Alle neustarten",
            ["B_Update"] = "Update",
            ["B_New"] = "Hinzufügen",
            ["L_Language"] = "Sprache:",
            ["Tab_Bots"] = "Bots",
            ["Tab_Hub"] = "Einstellungen",
            ["Tab_Logs"] = "Logs",
            ["Tab_Credits"] = "Credits",
            ["L_CreditsDevTitle"] = "Hauptentwickler",
            ["L_CreditsContribTitle"] = "Mitwirkende",
            ["L_CreditsSpecialTitle"] = "Besonderer Dank",
            ["Idle"] = "Inaktiv",
            ["FlexTrade"] = "Flex-Tausch",
            ["MultiTrade"] = "Multi-Tausch",
            ["LinkTrade"] = "Link-Tausch",
            ["SurpriseTrade"] = "Zaubertausch",
            ["Batch"] = "Stapel-Tausch",
            ["SeedCheck"] = "Seed-Prüfung",
            ["Clone"] = "Klonen",
            ["Dump"] = "Dumping",
            ["RaidBot"] = "Raid-Bot",
            ["EncounterLine"] = "Begegnung (Gehen)",
            ["Reset"] = "Begegnung (Reset)",
            ["DogBot"] = "Légenden-Bot",
            ["EggFetch"] = "Eier sammeln",
            ["FossilBot"] = "Fossilien-Bot",
            ["RemoteControl"] = "Fernsteuerung",
            ["LGPE"] = "LGPE",
            ["SWSH"] = "SWSH",
            ["BDSP"] = "SDLP",
            ["LA"] = "PLA",
            ["SV"] = "KPPU",
            ["PLZA"] = "PLZA",
            ["Dark Theme"] = "Dunkles Design",
            ["Light Theme"] = "Helles Design",
            ["IP Address"] = "IP-Adresse",
            ["Port"] = "Port",
            ["Protocol"] = "Protokoll",
            ["Routine"] = "Routine",
            ["WiFi"] = "WiFi",
            ["USB"] = "USB",
            ["Status"] = "Status",
        },
        ["ru"] = new()
        {
            ["B_NavBots"] = "  Боты",
            ["B_NavHub"] = "  Настройки",
            ["B_NavLogs"] = "  Логи",
            ["B_Credits"] = "  Авторы",
            ["B_HideTray"] = "  Свернуть",
            ["B_Start"] = "Запустить все",
            ["B_Stop"] = "Остановить все",
            ["B_Restart"] = "Перезапуск",
            ["B_Update"] = "Обновить",
            ["B_New"] = "Добавить",
            ["L_Language"] = "Язык:",
            ["Tab_Bots"] = "Боты",
            ["Tab_Hub"] = "Настройки",
            ["Tab_Logs"] = "Логи",
            ["Tab_Credits"] = "Авторы",
            ["L_CreditsDevTitle"] = "Главный разработчик",
            ["L_CreditsContribTitle"] = "Участники проекта",
            ["L_CreditsSpecialTitle"] = "Особая благодарность",
            ["Idle"] = "Ожидание",
            ["FlexTrade"] = "Гибкий обмен",
            ["MultiTrade"] = "Мульти-обмен",
            ["LinkTrade"] = "Связь",
            ["SurpriseTrade"] = "Чудо-обмен",
            ["Batch"] = "Пакетный обмен",
            ["SeedCheck"] = "Проверка сида",
            ["Clone"] = "Клонирование",
            ["Dump"] = "Дамп",
            ["RaidBot"] = "Рейд-бот",
            ["EncounterLine"] = "Встреча (Ходьба)",
            ["Reset"] = "Встреча (Сброс)",
            ["DogBot"] = "Легендарный бот",
            ["EggFetch"] = "Сбор яиц",
            ["FossilBot"] = "Фоссил-бот",
            ["RemoteControl"] = "Дистанция",
            ["LGPE"] = "LGPE",
            ["SWSH"] = "SWSH",
            ["BDSP"] = "BDSP",
            ["LA"] = "LA",
            ["SV"] = "SV",
            ["PLZA"] = "PLZA",
            ["Dark Theme"] = "Темная тема",
            ["Light Theme"] = "Светлая тема",
            ["IP Address"] = "IP-адрес",
            ["Port"] = "Порт",
            ["Protocol"] = "Протокол",
            ["Routine"] = "Рутина",
            ["WiFi"] = "WiFi",
            ["USB"] = "USB",
            ["Status"] = "Статус",
        },
        ["es"] = new()
        {
            ["B_NavBots"] = "  Bots",
            ["B_NavHub"] = "  Ajustes",
            ["B_NavLogs"] = "  Registros",
            ["B_Credits"] = "  Créditos",
            ["B_HideTray"] = "  Minimizar",
            ["B_Start"] = "Iniciar todo",
            ["B_Stop"] = "Detener todo",
            ["B_Restart"] = "Reiniciar todo",
            ["B_Update"] = "Actualizar",
            ["B_New"] = "Añadir",
            ["L_Language"] = "Idioma:",
            ["Tab_Bots"] = "Bots",
            ["Tab_Hub"] = "Ajustes",
            ["Tab_Logs"] = "Registros",
            ["Tab_Credits"] = "Créditos",
            ["L_CreditsDevTitle"] = "Desarrollador Principal",
            ["L_CreditsContribTitle"] = "Colaboradores",
            ["L_CreditsSpecialTitle"] = "Agradecimientos",
            ["Idle"] = "Inactivo",
            ["FlexTrade"] = "Intercambio Flex",
            ["MultiTrade"] = "Multi-intercambio",
            ["LinkTrade"] = "Conexión",
            ["SurpriseTrade"] = "Intercambio Mágico",
            ["Batch"] = "Lote",
            ["SeedCheck"] = "Verificar Seed",
            ["Clone"] = "Clonación",
            ["Dump"] = "Volcado",
            ["RaidBot"] = "Bot de Incursión",
            ["EncounterLine"] = "Encuentro (Caminata)",
            ["Reset"] = "Encuentro (Reset)",
            ["DogBot"] = "Bot Legendarios",
            ["EggFetch"] = "Recogida de Huevos",
            ["FossilBot"] = "Bot Fósiles",
            ["RemoteControl"] = "Control Remoto",
            ["LGPE"] = "LGPE",
            ["SWSH"] = "EB",
            ["BDSP"] = "DEPS",
            ["LA"] = "LPA",
            ["SV"] = "EV",
            ["PLZA"] = "PLZA",
            ["Dark Theme"] = "Tema Oscuro",
            ["Light Theme"] = "Tema Claro",
            ["IP Address"] = "Dirección IP",
            ["Port"] = "Puerto",
            ["Protocol"] = "Protocolo",
            ["Routine"] = "Rutina",
            ["WiFi"] = "WiFi",
            ["USB"] = "USB",
            ["Status"] = "Estado",
        },
        ["it"] = new()
        {
            ["B_NavBots"] = "  Bot",
            ["B_NavHub"] = "  Impostazioni",
            ["B_NavLogs"] = "  Registri",
            ["B_Credits"] = "  Crediti",
            ["B_HideTray"] = "  Riduci",
            ["B_Start"] = "Avvia tutto",
            ["B_Stop"] = "Ferma tutto",
            ["B_Restart"] = "Riavvia tutto",
            ["B_Update"] = "Aggiorna",
            ["B_New"] = "Aggiungi",
            ["L_Language"] = "Lingua:",
            ["Tab_Bots"] = "Bot",
            ["Tab_Hub"] = "Impostazioni",
            ["Tab_Logs"] = "Registri",
            ["Tab_Credits"] = "Crediti",
            ["L_CreditsDevTitle"] = "Sviluppatore Principale",
            ["L_CreditsContribTitle"] = "Collaboratori",
            ["L_CreditsSpecialTitle"] = "Ringraziamenti",
            ["Idle"] = "Inattivo",
            ["FlexTrade"] = "Scambio Flex",
            ["MultiTrade"] = "Multi-scambio",
            ["LinkTrade"] = "Connessione",
            ["SurpriseTrade"] = "Scambio Magico",
            ["Batch"] = "Batch",
            ["SeedCheck"] = "Verifica Seed",
            ["Clone"] = "Clonazione",
            ["Dump"] = "Dump",
            ["RaidBot"] = "Bot Raid",
            ["EncounterLine"] = "Incontro (Camminata)",
            ["Reset"] = "Incontro (Reset)",
            ["DogBot"] = "Bot Leggendari",
            ["EggFetch"] = "Raccolta Uova",
            ["FossilBot"] = "Bot Fossili",
            ["RemoteControl"] = "Controllo Remoto",
            ["LGPE"] = "LGPE",
            ["SWSH"] = "EB",
            ["BDSP"] = "DEPS",
            ["LA"] = "LPA",
            ["SV"] = "SV",
            ["PLZA"] = "PLZA",
            ["Dark Theme"] = "Tema Scuro",
            ["Light Theme"] = "Tema Chiaro",
            ["IP Address"] = "Indirizzo IP",
            ["Port"] = "Porta",
            ["Protocol"] = "Protocollo",
            ["Routine"] = "Routine",
            ["WiFi"] = "WiFi",
            ["USB"] = "USB",
            ["Status"] = "Stato",
        },
        ["ja"] = new()
        {
            ["B_NavBots"] = "  ボット",
            ["B_NavHub"] = "  設定",
            ["B_NavLogs"] = "  ログ",
            ["B_Credits"] = "  クレジット",
            ["B_HideTray"] = "  最小化",
            ["B_Start"] = "すべて開始",
            ["B_Stop"] = "すべて停止",
            ["B_Restart"] = "すべて再起動",
            ["B_Update"] = "更新",
            ["B_New"] = "追加",
            ["L_Language"] = "言語:",
            ["Tab_Bots"] = "ボット",
            ["Tab_Hub"] = "設定",
            ["Tab_Logs"] = "ログ",
            ["Tab_Credits"] = "クレジット",
            ["L_CreditsDevTitle"] = "メイン開発者",
            ["L_CreditsContribTitle"] = "コントリビューター",
            ["L_CreditsSpecialTitle"] = "特別感謝",
            ["Idle"] = "待機中",
            ["FlexTrade"] = "フレックストレード",
            ["MultiTrade"] = "マルチトレード",
            ["LinkTrade"] = "通信交換",
            ["SurpriseTrade"] = "マジカル交換",
            ["Batch"] = "一括交換",
            ["SeedCheck"] = "シードチェック",
            ["Clone"] = "クローン",
            ["Dump"] = "ダンプ",
            ["RaidBot"] = "レイドボット",
            ["EncounterLine"] = "エンカウント (歩行)",
            ["Reset"] = "エンカウント (リセット)",
            ["DogBot"] = "伝説ボット",
            ["EggFetch"] = "卵収集",
            ["FossilBot"] = "化石ボット",
            ["RemoteControl"] = "リモートコントロール",
            ["LGPE"] = "LGPE",
            ["SWSH"] = "剣盾",
            ["BDSP"] = "BDSP",
            ["LA"] = "レジェンズ",
            ["SV"] = "SV",
            ["PLZA"] = "PLZA",
            ["Dark Theme"] = "ダークテーマ",
            ["Light Theme"] = "ライトテーマ",
            ["IP Address"] = "IPアドレス",
            ["Port"] = "ポート",
            ["Protocol"] = "プロトコル",
            ["Routine"] = "ルーチン",
            ["WiFi"] = "WiFi",
            ["USB"] = "USB",
            ["Status"] = "ステータス",
        },
        ["ko"] = new()
        {
            ["B_NavBots"] = "  봇",
            ["B_NavHub"] = "  설정",
            ["B_NavLogs"] = "  로그",
            ["B_Credits"] = "  크레딧",
            ["B_HideTray"] = "  최소화",
            ["B_Start"] = "모두 시작",
            ["B_Stop"] = "모두 중지",
            ["B_Restart"] = "모두 재시작",
            ["B_Update"] = "업데이트",
            ["B_New"] = "추가",
            ["L_Language"] = "언어:",
            ["Tab_Bots"] = "봇",
            ["Tab_Hub"] = "설정",
            ["Tab_Logs"] = "로그",
            ["Tab_Credits"] = "크레딧",
            ["L_CreditsDevTitle"] = "주요 개발자",
            ["L_CreditsContribTitle"] = "기여자",
            ["L_CreditsSpecialTitle"] = "특별 감사",
            ["Idle"] = "대기",
            ["FlexTrade"] = "플렉스 트레이드",
            ["MultiTrade"] = "멀티 트레이드",
            ["LinkTrade"] = "통신교환",
            ["SurpriseTrade"] = "매지컬교환",
            ["Batch"] = "일괄교환",
            ["SeedCheck"] = "시드체크",
            ["Clone"] = "클론",
            ["Dump"] = "덤프",
            ["RaidBot"] = "레이드봇",
            ["EncounterLine"] = "인카운터 (걷기)",
            ["Reset"] = "인카운터 (리셋)",
            ["DogBot"] = "전설봇",
            ["EggFetch"] = "알 수집",
            ["FossilBot"] = "화석봇",
            ["RemoteControl"] = "리모트 컨트롤",
            ["LGPE"] = "LGPE",
            ["SWSH"] = "소실",
            ["BDSP"] = "브다샤펄",
            ["LA"] = "레알세",
            ["SV"] = "SV",
            ["PLZA"] = "PLZA",
            ["Dark Theme"] = "다크 테마",
            ["Light Theme"] = "라이트 테마",
            ["IP Address"] = "IP 주소",
            ["Port"] = "포트",
            ["Protocol"] = "프로토콜",
            ["Routine"] = "루틴",
            ["WiFi"] = "WiFi",
            ["USB"] = "USB",
            ["Status"] = "상태",
        }
    };

    public static string Translate(string key, string language)
    {
        if (Translations.TryGetValue(language, out var langDict) && langDict.TryGetValue(key, out var translated))
            return translated;
        return key;
    }

    public static void ApplyLocalization(Control control, string language)
    {
        foreach (Control c in control.Controls)
        {
            if (!string.IsNullOrEmpty(c.Name))
            {
                var translated = Translate(c.Name, language);
                if (translated != c.Name)
                {
                    c.Text = translated;
                }
            }

            if (c is TabControl tc)
            {
                foreach (TabPage tp in tc.TabPages)
                {
                    var translated = Translate(tp.Name, language);
                    if (translated != tp.Name)
                    {
                        tp.Text = translated;
                    }
                    ApplyLocalization(tp, language);
                }
            }
            else if (c.HasChildren)
            {
                ApplyLocalization(c, language);
            }
        }
    }
}
